// Short text printed on the card tiles. Written by hand in one style:
// a rulebook keyword ("Combo enter:", "When flipped:", ...) then the effect.
// It is display only. The rules are the readings in js/cards-data.js
// (shown in full in the side panel), and the engine never reads this file.
// Style: "+2 Power", "+1 energy", "gain/lose N life", "draw 1, discard 1",
// "next to a 3", "flip" = turn face down, "this combo" = the combo it's in.
(function (root) {
  'use strict';
  root.Solo = root.Solo || {};
  root.Solo.CARD_TEXT = {
    // ---------------------------------------------------------- characters
    'C-asher': 'When you play a Red 1–3: +1 Power.',
    'C-spring': 'When you play a Blue 4+: flip your opponent\'s last combo card. Start of clash: +1 Power per face-down card in your opponent\'s combo.',
    'C-sonny': 'When you play a Yellow card: if you have less Power, +1 Power; if you have more, draw 1, discard 1.',
    'C-forest': 'When you play a Green card exactly 3 higher than your opponent\'s last combo card (or 0): +1 energy.',
    'C-noct': 'Your face-down cards are worth 2 instead of 0.',
    'C-ember': 'When you play an even card: you may play a 1 from your discard pile.',
    'C-cian': 'When you play an odd card: flip it, then take a 2 from your discard pile into your hand.',
    'C-leo': 'When you play an odd card: put your top deck card face up into your combo. When you play an even card: you may return a face-down combo card to your hand.',
    'C-young': 'When you play an even card: discard your top deck card face down. End of clash: with 5+ face-down cards in your discard pile, your max energy becomes 18.',
    'C-evelyn': 'When you play a 3: each player puts a card from hand face down into their combo. Start of clash: turn all face-down cards face up (number only, no abilities).',
    'C-vlad': 'Clash win: gain 2 life.',
    'C-victoria': 'End of clash: draw 2. Clash win: deal exactly 1 damage instead.',
    'C-master': 'Start of clash: with a run of 3, +3 Power. With a run of 5, also discard a card from your opponent\'s combo.',
    'C-jack': 'When you play a card that makes a pair: +1 energy.',
    'C-dante': 'Start of clash: with 3+ colors in your combo, your opponent discards their top 5 deck cards. With all 5 colors, they also lose 1 life per color in their combo.',

    // ---------------------------------------------------------- red
    'R1-flame': 'Combo enter: lose 3 life, draw 1.',
    'R1-phoenix': 'Combo enter: +1 Power per 1 in your combo.',
    'R1-blood': 'Combo enter: draw 1, discard 1.',
    'R2-flame': 'Combo enter: both players lose 2 life.',
    'R2-phoenix': 'Combo enter: if next to a 1, gain 2 life.',
    'R2-blood': 'Combo enter: if you have more Power, lose 2 Power and draw 1.',
    'R3-flame': 'Combo enter: if your combo has a run of 3, return cards totaling exactly 3 from your discard pile to your hand.',
    'R3-phoenix': 'Combo enter: if you have more Power, gain 3 life.',
    'R3-blood': 'Combo enter: if next to a 3, +3 Power.',
    'R4-flame': 'Combo enter: if you have more Power, +2 Power.',
    'R4-phoenix': 'Combo enter: lose 1 life, then discard a 0 from your opponent\'s combo.',
    'R4-blood': 'Feint: play a 3 from your discard pile, then draw 1.',
    'R5-flame': 'Combo enter: if you have less Power, +4 Power.',
    'R5-phoenix': 'Combo enter: lose 2 life, then flip a card in your opponent\'s combo.',
    'R5-blood': 'Combo enter: discard your hand, draw 3.',
    'R6-flame': 'Style: when your own cards would make you lose life, gain that much instead.',
    'R6-phoenix': 'Combo enter: deal damage equal to your Power. Your opponent may discard cards from hand to reduce it by their total value.',
    'R6-blood': 'Feint: +X Power, where X is 10 minus your life.',
    'R7-flame': 'Start of clash: drop to 1 life. You take no damage this clash.',
    'R7-phoenix': 'Clash win: gain life equal to the damage dealt.',
    'R7-blood': 'Style: your Red cards cost 1 less.',
    'R8-flame': 'End of clash: gain 6 life.',
    'R8-phoenix': 'End of clash: choose another card in your combo. It stays as your first card next round.',
    'R8-blood': 'End of clash: draw 3.',
    'R9-flame': 'Costs 1 less per 1 in your combo.',
    'R9-phoenix': 'Costs 1 less per life you lost this round.',
    'R9-blood': 'Costs 1 less per Power you have.',

    // ---------------------------------------------------------- blue
    'U1-river': 'Patience. When flipped: your opponent loses 2 Power.',
    'U1-check': 'Combo enter: if next to a 1 or a 0, +1 energy.',
    'U1-cyber': 'Patience. When flipped: draw 1, discard 1.',
    'U2-river': 'Combo enter: +1 Power per face-down card in your opponent\'s combo.',
    'U2-check': 'Combo enter: flip a card worth 2 or less in your opponent\'s combo.',
    'U2-cyber': 'When flipped: copy the combo enter of another card in your combo.',
    'U3-river': 'Combo enter: draw 1.',
    'U3-check': 'Combo enter: discard your top deck card once per odd card in both combos.',
    'U3-cyber': 'Patience. When flipped: flip a card worth 3 or less in your opponent\'s combo.',
    'U4-river': 'Patience. When flipped: your opponent puts their top 2 deck cards face down into their combo.',
    'U4-check': 'When flipped: your opponent puts their top 2 deck cards face down into their combo.',
    'U4-cyber': 'Combo enter: +1 Power per face-down card in your combo.',
    'U5-river': 'When flipped: your opponent puts a card from their hand face down into their combo.',
    'U5-check': 'Combo enter: flip a card in your combo (this one allowed).',
    'U5-cyber': 'Combo enter: if your combo has two or more 0s, flip a card in your opponent\'s combo.',
    'U6-river': 'Patience. When flipped: discard your top 3 deck cards.',
    'U6-check': 'Combo enter: if your opponent has more Power, they lose 3 Power.',
    'U6-cyber': 'Combo enter: +1 Power per face-down card in both combos.',
    'U7-river': 'Combo enter: discard your top deck cards, one per Power you have.',
    'U7-check': 'Combo enter: if next to a 0, your opponent flips one of their combo cards.',
    'U7-cyber': 'Combo enter: gain 1 life per face-down card in both combos.',
    'U8-river': 'Start of clash: you may flip a card in your combo. It stays as your first card next round.',
    'U8-check': 'End of clash: if you dealt 2 or less damage, draw 2.',
    'U8-cyber': 'Combo enter: if your combo has two or more 0s, your opponent loses 2 energy.',
    'U9-river': 'Combo enter: return all your face-down combo cards to your hand. +1 energy each.',
    'U9-check': 'Combo enter: if next to a 0, choose a card in either combo and flip it 4 times (its When flipped triggers 4 times).',
    'U9-cyber': 'Costs 2 less per face-down card in your combo.',

    // ---------------------------------------------------------- yellow
    'Y1-sun': 'When discarded: your opponent gets +2 Power; you get +1 energy.',
    'Y1-lion': 'When discarded: +1 Power.',
    'Y1-flash': 'Reaction: when one of your combo cards would be flipped, discard this instead.',
    'Y2-sun': 'Combo enter: +1 Power per 2 cards in your hand.',
    'Y2-lion': 'Combo enter / When flipped: if next to a 2, +2 Power.',
    'Y2-flash': 'Can be played next to a 0 of any color.',
    'Y3-sun': 'Combo enter / When flipped: if it ends a run of 3, draw 1.',
    'Y3-lion': 'Combo enter: if next to a 0, your opponent loses 2 Power.',
    'Y3-flash': 'Can be played next to a 0 of any color.',
    'Y4-sun': 'Reaction: when you discard another card, you may discard this to return that card to your hand.',
    'Y4-lion': 'Can be played next to a 0 of any color.',
    'Y4-flash': 'Combo enter: turn a face-down card in your combo face up. If it\'s 4 or more, it goes to your hand.',
    'Y5-sun': 'Can be played next to a 0 of any color.',
    'Y5-lion': 'Style: +1 energy whenever you discard a card.',
    'Y5-flash': 'Combo enter: if next to a 0, +3 Power.',
    'Y6-sun': 'Combo enter: you may discard a card from your combo to discard a card worth 5 or less from your opponent\'s combo.',
    'Y6-lion': 'Combo enter: if next to a 0, your opponent puts their top deck card face down into their combo.',
    'Y6-flash': 'Can be played next to a 0 of any color.',
    'Y7-sun': 'When discarded: +3 energy.',
    'Y7-lion': 'Combo enter: you may discard 2 cards from your combo for +2 energy.',
    'Y7-flash': 'Can be played next to a 0 of any color.',
    'Y8-sun': 'Combo enter: discard a card from your opponent\'s combo.',
    'Y8-lion': 'Combo enter: turn a face-down card in your combo face up.',
    'Y8-flash': 'When discarded: +4 Power.',
    'Y9-sun': 'Combo enter: discard your hand, draw 5.',
    'Y9-lion': 'Costs 1 less per card you discarded this round.',
    'Y9-flash': 'When discarded: shuffle your discard pile (this one included) into your deck.',

    // ---------------------------------------------------------- green
    'G1-forest': 'Combo enter: if your combo totals more than 10, +2 energy.',
    'G1-mantis': 'Reaction: when your opponent would discard one of your combo cards, discard this instead.',
    'G1-life': 'Reaction: when your opponent would flip one of your combo cards, discard this instead.',
    'G2-forest': 'Combo enter: gain life equal to your Power.',
    'G2-mantis': 'Patience. When flipped: discard your top 2 deck cards face down.',
    'G2-life': 'Combo enter: if your combo total beats your opponent\'s, +2 Power.',
    'G3-forest': 'Combo enter: if your opponent\'s last combo card is a 0, +2 energy.',
    'G3-mantis': 'Style: when you play a card, you may pay 1 energy so each player draws 1.',
    'G3-life': 'Combo enter: you may discard a card from your combo for +1 energy.',
    'G4-forest': 'End of clash: +3 energy (can go over max).',
    'G4-mantis': 'Style: your combo can\'t be rearranged or swapped.',
    'G4-life': 'Combo enter: if it ends a run of 3+, +5 energy.',
    'G5-forest': 'Combo enter: if next to a 5, look at your top 2 deck cards. Discard one face down; play the other for free.',
    'G5-mantis': 'Patience. When flipped: you may discard 2 cards from hand face down for +3 energy.',
    'G5-life': 'Combo enter: you may pay energy equal to 10 minus the card next to it, to draw 2.',
    'G6-forest': 'Combo enter: if next to a 6, +6 Power.',
    'G6-mantis': 'Reaction: when your opponent plays a 4 or less, you may discard this. They discard a card from their combo.',
    'G6-life': 'Combo enter: if your lowest card beats your opponent\'s highest, +4 Power.',
    'G7-forest': 'Combo enter: rearrange both combos however you like.',
    'G7-mantis': 'Free to play if it\'s your only card in hand and your opponent has more Power.',
    'G7-life': 'Combo enter: each player discards 2 random cards from hand.',
    'G8-forest': 'Start of clash: if your combo has more pairs, +6 Power.',
    'G8-mantis': 'Style: +1 energy when you Engage without starting a clash.',
    'G8-life': 'Combo enter: return another combo card to your hand. Gain energy equal to its value + 1.',
    'G9-forest': 'Combo enter: copy the combo enter of another card in your combo.',
    'G9-mantis': 'Costs 1 less per 3 cards in your discard pile.',
    'G9-life': 'Combo enter: spend any amount of energy. +5 Power per energy spent.',

    // ---------------------------------------------------------- black
    'K1-umbra': 'Patience. When flipped: flip the first card of your opponent\'s combo.',
    'K1-ink': 'Can be played next to any color.',
    'K1-death': 'When flipped: if your combo has 3+ colors, draw 1.',
    'K2-umbra': 'Combo enter: put a card from your discard pile into your opponent\'s combo.',
    'K2-ink': 'Style: cards cost 1 more to play into this combo.',
    'K2-death': 'Combo enter: flip a face-up Black card in either combo.',
    'K3-umbra': 'Forced: discard this when a card higher than 3 is played into its combo.',
    'K3-ink': 'Combo enter: put a card from your discard pile into your opponent\'s combo.',
    'K3-death': 'Combo enter: you may flip a card in your combo to draw 2, discard 1.',
    'K4-umbra': 'Combo enter: swap the first and last cards of your opponent\'s combo.',
    'K4-ink': 'When flipped: return a face-down card from your combo to your hand.',
    'K4-death': 'Combo enter: put a card from your discard pile into your opponent\'s combo.',
    'K5-umbra': 'Also counts as Blue.',
    'K5-ink': 'Also counts as Red.',
    'K5-death': 'Also counts as Green.',
    'K6-umbra': 'Combo enter: rearrange your opponent\'s combo however you like.',
    'K6-ink': 'Style: cards played into this combo don\'t trigger their combo enter.',
    'K6-death': 'Combo enter: put a card from your discard pile into your opponent\'s combo.',
    'K7-umbra': 'Combo enter: draw 2.',
    'K7-ink': 'Combo enter: flip all your other combo cards. If any flipped, put your top 2 deck cards face down into your combo.',
    'K7-death': 'Combo enter: if your combo has 2+ face-down cards, turn one face up.',
    'K8-umbra': 'Style: cards in this combo can\'t be flipped.',
    'K8-ink': 'Style: whenever a card is played into this combo, its owner discards their top deck card.',
    'K8-death': 'Combo enter: play up to five 1s of different colors from your discard pile.',
    'K9-umbra': 'Combo enter: put a card from your discard pile face down into your combo.',
    'K9-ink': 'Combo enter: discard this. End of clash: if it\'s still in a combo, it stays for next round.',
    'K9-death': 'Style: face-down cards in this combo are worth 3 more.',
  };
  // Keywords shown in bold at the start of each ability.
  root.Solo.CARD_KEYWORDS = ['Combo enter / When flipped', 'Combo enter', 'Patience', 'When flipped', 'When discarded',
    'Feint', 'Reaction', 'Forced', 'Style', 'Start of clash', 'End of clash', 'Clash win'];
})(typeof window !== 'undefined' ? window : globalThis);
