# Builds js/cards-data.js from the designer's spreadsheet (source/*.xlsx)
# plus the plain-English readings in readings.md, with rulings.md applied.
# Run from the repo root:  powershell -ExecutionPolicy Bypass -File tools\build-cards.ps1
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$xlsx = Join-Path $root 'source\Solo the Card game.xlsx'
$tmp = Join-Path ([IO.Path]::GetTempPath()) ('solo-xlsx-' + [Guid]::NewGuid())
New-Item -ItemType Directory $tmp | Out-Null
Copy-Item $xlsx "$tmp\book.zip"
Expand-Archive "$tmp\book.zip" "$tmp\u"
$d = "$tmp\u\xl"

[xml]$ss = Get-Content -Raw -Encoding UTF8 "$d\sharedStrings.xml"
$strs = @(); foreach ($si in $ss.sst.si) { $strs += $si.InnerText }

function Read-Sheet($n) {
  [xml]$sh = Get-Content -Raw -Encoding UTF8 "$d\worksheets\sheet$n.xml"
  $rows = @()
  foreach ($r in $sh.worksheet.sheetData.row) {
    $row = @{}
    foreach ($c in $r.c) {
      $v = $c.v
      if ($c.t -eq 's') { $v = $strs[[int]$v] }
      $col = ($c.r -replace '\d', '')
      $row[$col] = "$v"
    }
    $rows += , $row
  }
  return $rows
}

# Readings: "- Color N Name — text" and "- Color Name (Archetype) — text"
$readings = @{}
foreach ($line in Get-Content -Encoding UTF8 (Join-Path $root 'readings.md')) {
  $dash = [string][char]0x2014
  if ($line -match ('^- (Red|Blue|Yellow|Green|Black) (.+?) ' + $dash + ' (.+)$')) {
    $key = "$($Matches[1]) $($Matches[2])" -replace ' \([^)]*\)$', ''
    $readings[$key] = $Matches[3]
  }
}

# rulings.md overrides (these win over readings.md)
$rulings = @{
  'Yellow 9 Lion Finisher' = 'Costs 1 less energy for each card YOU discarded this round, from any zone (the opponent''s discards don''t count; reset-step-3 cleanup doesn''t count). [RULING]'
  'Yellow 4 Sun Cross'     = 'Reaction Feint (doesn''t use your action): while in your combo, when you discard another card you may discard Sun Cross from your combo; if you do, return that card to your hand. [RULING]'
  'Green Forest Oak'       = 'Whenever you play a Green card whose value is EXACTLY 3 higher than your opponent''s last played (rightmost) combo card (0 if empty or face down), gain +1 energy. [RULING]'
  'Blue 9 Check Finisher'  = 'Combo enter: if the card next to it is a 0, choose one face-up card in either combo and flip it 4 times: it turns face down once and its "when flipped" ability triggers 4 times (for the player whose combo it is in). A reaction that stops the flip (Flash Jab, Life Jab) or Umbra Roundhouse stops all four. [RULING]'
}

$colors = @{ 4 = 'Red'; 5 = 'Blue'; 6 = 'Yellow'; 7 = 'Green'; 8 = 'Black' }
$letter = @{ Red = 'R'; Blue = 'U'; Yellow = 'Y'; Green = 'G'; Black = 'K' }
$moves = @('', 'Jab', 'Chop', 'Straight', 'Cross', 'Hook', 'Uppercut', 'Snap', 'Roundhouse', 'Finisher')
$out = @()
$missing = @()

# Characters (sheets 1-3)
$groups = @{ 1 = 'Mono'; 2 = 'Number'; 3 = 'Wild' }
foreach ($n in 1..3) {
  $rows = Read-Sheet $n
  foreach ($row in $rows[1..($rows.Count - 1)]) {
    if (-not $row['A']) { continue }
    $name = ($row['A'] -replace '\s+', ' ').Trim()
    $color = $row['B'].Trim()
    $key = "$color $name"
    $slug = ($name.Split(' ')[0]).ToLower()
    if (-not $readings.ContainsKey($key)) { $missing += $key }
    $reading = if ($rulings.ContainsKey($key)) { $rulings[$key] } else { $readings[$key] }
    $out += [ordered]@{
      id = "C-$slug"; kind = 'character'; name = $name; color = $color; number = $null
      family = $groups[$n]; archetype = $row['D'].Trim(); text = $row['E'].Trim(); reading = $reading
    }
  }
}

# Numbered cards (sheets 4-8). Family names come from column H of rows 2-4.
foreach ($n in 4..8) {
  $color = $colors[$n]
  $rows = Read-Sheet $n
  $fams = @(1, 2, 3 | ForEach-Object { ($rows[$_]['H'] -replace '\([^)]*\)', '').Trim() })
  for ($i = 1; $i -le 27; $i++) {
    $row = $rows[$i]
    $num = [int][double]$row['C']
    $fam = $fams[($i - 1) % 3]
    $name = "$fam $($moves[$num])"
    $key = "$color $num $name"
    if (-not $readings.ContainsKey($key)) { $missing += $key }
    $reading = if ($rulings.ContainsKey($key)) { $rulings[$key] } else { $readings[$key] }
    $out += [ordered]@{
      id = "$($letter[$color])$num-$($fam.ToLower())"; kind = 'number'; name = $name; color = $color; number = $num
      family = $fam; sheetName = ($row['A'] -replace '\s+', ' ').Trim(); text = $row['D'].Trim(); reading = $reading
    }
  }
}

Remove-Item -Recurse -Force $tmp
if ($missing.Count) { throw "No reading found for: $($missing -join ', ')" }
$json = $out | ConvertTo-Json -Depth 4
$js = "// GENERATED by tools/build-cards.ps1 from source/Solo the Card game.xlsx + readings.md + rulings.md. Do not edit by hand.`n" +
      "window.SOLO_CARD_DATA = $json;`n"
[IO.File]::WriteAllText((Join-Path $root 'js\cards-data.js'), $js, (New-Object Text.UTF8Encoding($false)))
"Wrote $($out.Count) cards"
